exclude: '.git|.tox'
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      # - id: detect-aws-credentials
      # - id: detect-private-key
      # - id: check-merge-conflict
  - repo: https://github.com/psf/black
    rev: 21.6b0
    hooks:
      - id: black
  - repo: https://github.com/timothycrosley/isort
    rev: 5.6.4
    hooks:
      - id: isort
  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2  # pick a git hash / tag to point to
    hooks:
      - id: flake8
  - repo: local
    hooks:
    - id: mypy
      name: mypy
      entry: make mypy
      language: system
  - repo: local
    hooks:
    - id: unittest
      name: unittests
      entry: make test
      language: system
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v0.902  # Use the sha / tag you want to point at
  #   hooks:
  #   - id: mypy
  #     pass_filenames: false
  # - repo: local
  #   id: unittest
  #   name: unittest
  #   entry: make test
  #   language: python
